### PR TITLE
Update input design

### PR DESCRIPTION
**Pull request by BugReportOnWeb**
Kar do please :cat:

### CODE REVIEW

**Comment by UdhbhavSinghRana** [comment]
say my name

**Comment by UdhbhavSinghRana** [comment]
pols aa gyi pols

**Comment by BugReportOnWeb** [comment]
Rana ji mujhe maf karna :cry:

**Comment by UdhbhavSinghRana** [comment]
are ye to contributer hi h

**Comment by BugReportOnWeb** [comment]
daro na, ye to sirf modifive kiya hai :smile:

**Comment by UdhbhavSinghRana** [comment]
🤨

**Comment by BugReportOnWeb** [comment]
<VINE BOOM EFFECT> :astonished:

**Pull request merged**
